### ISSUE TITLE
Add visible field to content

### ISSUE THREAD

**Issue by aisflat439** [DevinColin/pet-care-co#17]
She may want to make certain content cards active or inactive at different times, maybe she's running a sign up in the month of October special or something. I don't think we should go crazy but allowing for this might be worthwhile. What do you think?

**Comment by colin-j-arpe** [comment]
Yeah, we could put an entry for every page in the content table (even ones w no additional content), then add a visible boolean which the header layout would check when filling out the nav menu.  I'm adding another content column later so I'll do this too
